-- instructors (can login)
insert into instructors (name, image, about, is_delete, email, password) values ('Delmer Baumbach', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', 'Tenetur quia minima minima quia quas veniam rem. In in voluptate voluptatum cumque suscipit voluptas. Ex autem dolorum illo omnis numquam. Assumenda perspiciatis in eos provident iusto voluptates quaerat.', false, 'admin1@mail.com', '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92');
insert into instructors (name, image, about, is_delete, email, password) values ('Ewell Connell', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', 'Laboriosam tempore quia quae sed ullam tempore eos. Sed incidunt quisquam ipsum nam architecto deleniti sequi deleniti sed. Ratione earum nihil. Ipsa veniam sint blanditiis quod iste voluptas.', false, 'admin2@mail.com', '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92');
insert into instructors (name, image, about, is_delete, email, password) values ('Camilla Fritsch', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', 'Aut quis minus sequi. Repellendus veniam dolor quas. Quibusdam et numquam animi autem itaque sint eius occaecati numquam.', false, 'admin3@mail.com', '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92');
insert into instructors (name, image, about, is_delete, email, password) values ('Greta Langworth', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', 'Aliquid laborum deleniti optio molestiae quo voluptatum in. Culpa nostrum consequatur quo saepe. Autem rem provident suscipit tempora. Id iste reprehenderit.', false, 'admin4@mail.com', '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92');
insert into instructors (name, image, about, is_delete, email, password) values ('Ronny Veum', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', 'Modi quod possimus tempore illo ut repellendus voluptatem dolores. Unde tempore velit. Ut consequatur eius quidem cum sit. Commodi qui laudantium animi deserunt et.', false, 'admin5@mail.com', '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92');


-- classes
insert into classes (title, description, is_delete, frequency, image, color) values ('Recreation', 'Atque et saepe id magnam. Distinctio et omnis magni. Minima facilis quod reprehenderit debitis. Quaerat nostrum aliquid eos voluptatum numquam. Omnis quam veritatis iusto nobis voluptatem soluta. Soluta aspernatur nisi qui et voluptatibus at voluptates quam.', false, 'Deserunt deserunt nesciunt sint.', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', '#AAB3AB');
insert into classes (title, description, is_delete, frequency, image, color) values ('Novice', 'Qui quibusdam ex et dolores deleniti. Quas est neque cumque et. Dolorem nemo eius facilis autem saepe aperiam earum veritatis recusandae. Nihil sit itaque at. Reiciendis deleniti optio placeat quasi. Corrupti nemo cum debitis.', false, 'Et voluptatem totam ullam facilis.', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', '#C4CBB7');
insert into classes (title, description, is_delete, frequency, image, color) values ('Intermediate', 'Ducimus unde reprehenderit quae temporibus iste. Aut ex impedit. Natus eum nihil ut ut est libero quod est magnam. Non commodi et eum in sequi voluptatum voluptatem eos placeat.', false, 'Sequi cum voluptate porro aut enim voluptatem impedit quod est.', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', '#EBEFC9');
insert into classes (title, description, is_delete, frequency, image, color) values ('Advanced', 'Animi unde ut quia commodi architecto molestiae odio doloremque temporibus. Ipsam quia voluptas voluptas amet dignissimos dolor ea quia. A nihil aspernatur eum ut et ut earum. Atque qui sed aut error rerum.', false, 'Voluptates quia vitae.', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', '#EEE0B7');
insert into classes (title, description, is_delete, frequency, image, color) values ('Adult', 'Qui fugit magnam rerum magnam facere labore ad aut voluptas. A voluptatem consequatur. Magnam impedit ipsam et id recusandae dolorum. Consequatur rerum quia impedit ut dolorem. Optio necessitatibus soluta expedita animi repellendus aliquam. Sequi nisi distinctio.', false, 'Illo ducimus tempore quibusdam necessitatibus.', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', '#E8CAAF');


-- sessions (CLASS 1)
insert into sessions (class_id, start_datetime, end_datetime, location, is_delete) values (1, 1592553600000, 1592560800000, 'Bishan', false);
insert into sessions (class_id, start_datetime, end_datetime, location, is_delete) values (1, 1593158400000, 1593165600000, 'Bishan', false);
insert into sessions (class_id, start_datetime, end_datetime, location, is_delete) values (1, 1593763200000, 1593770400000, 'Bishan', false);
insert into sessions (class_id, start_datetime, end_datetime, location, is_delete) values (1, 1594368000000, 1594375200000, 'Bishan', false);


-- sessions (CLASS 2)
insert into sessions (class_id, start_datetime, end_datetime, location, is_delete) values (2, 1592289000000, 1592296200000, 'Beier Hollow', false);
insert into sessions (class_id, start_datetime, end_datetime, location, is_delete) values (2, 1592893800000, 1592901000000, 'Jettie Stravenue', false);
insert into sessions (class_id, start_datetime, end_datetime, location, is_delete) values (2, 1593498600000, 1593505800000, 'Hand Extensions', false);
insert into sessions (class_id, start_datetime, end_datetime, location, is_delete) values (2, 1594103400000, 1594110600000, 'Hills Springs', false);
insert into sessions (class_id, start_datetime, end_datetime, location, is_delete) values (2, 1592461800000, 1592469000000, 'Elias Locks', false);
insert into sessions (class_id, start_datetime, end_datetime, location, is_delete) values (2, 1593066600000, 1593073800000, 'Auer Village', false);
insert into sessions (class_id, start_datetime, end_datetime, location, is_delete) values (2, 1593671400000, 1593678600000, 'Davis Gateway', false);
insert into sessions (class_id, start_datetime, end_datetime, location, is_delete) values (2, 1594276200000, 1594283400000, 'Brannon Village', false);
insert into sessions (class_id, start_datetime, end_datetime, location, is_delete) values (2, 1592634600000, 1592641800000, 'Winifred Camp', false);
insert into sessions (class_id, start_datetime, end_datetime, location, is_delete) values (2, 1593239400000, 1593246600000, 'McGlynn Fork', false);
insert into sessions (class_id, start_datetime, end_datetime, location, is_delete) values (2, 1593844200000, 1593851400000, 'VonRueden Crescent', false);
insert into sessions (class_id, start_datetime, end_datetime, location, is_delete) values (2, 1594449000000, 1594456200000, 'Keely Ports', false);


-- sessions (CLASS 3)
insert into sessions (class_id, start_datetime, end_datetime, location, is_delete) values (3, 1592359200000, 1592366400000, 'Aryanna Oval', false);
insert into sessions (class_id, start_datetime, end_datetime, location, is_delete) values (3, 1592964000000, 1592971200000, 'Hiram Parkway', false);
insert into sessions (class_id, start_datetime, end_datetime, location, is_delete) values (3, 1593568800000, 1593576000000, 'Briana Falls', false);
insert into sessions (class_id, start_datetime, end_datetime, location, is_delete) values (3, 1594173600000, 1594180800000, 'Rosamond Garden', false);


-- sessions (CLASS 4)
insert into sessions (class_id, start_datetime, end_datetime, location, is_delete) values (4, 1592456400000, 1592463600000, 'Zemlak Roads', false);
insert into sessions (class_id, start_datetime, end_datetime, location, is_delete) values (4, 1593061200000, 1593068400000, 'Prosacco Neck', false);
insert into sessions (class_id, start_datetime, end_datetime, location, is_delete) values (4, 1593666000000, 1593673200000, 'McGlynn Mission', false);
insert into sessions (class_id, start_datetime, end_datetime, location, is_delete) values (4, 1594270800000, 1594278000000, 'Gottlieb Knoll', false);
insert into sessions (class_id, start_datetime, end_datetime, location, is_delete) values (4, 1592542800000, 1592550000000, 'Crist Lane', false);
insert into sessions (class_id, start_datetime, end_datetime, location, is_delete) values (4, 1593147600000, 1593154800000, 'Ardella Overpass', false);
insert into sessions (class_id, start_datetime, end_datetime, location, is_delete) values (4, 1593752400000, 1593759600000, 'Genevieve Forge', false);
insert into sessions (class_id, start_datetime, end_datetime, location, is_delete) values (4, 1594357200000, 1594364400000, 'June Drive', false);


-- sessions (CLASS 5)
insert into sessions (class_id, start_datetime, end_datetime, location, is_delete) values (5, 1592616600000, 1592623800000, 'Kaylie Falls', false);
insert into sessions (class_id, start_datetime, end_datetime, location, is_delete) values (5, 1593221400000, 1593228600000, 'Cordie Wall', false);
insert into sessions (class_id, start_datetime, end_datetime, location, is_delete) values (5, 1593826200000, 1593833400000, 'Ceasar Camp', false);
insert into sessions (class_id, start_datetime, end_datetime, location, is_delete) values (5, 1594431000000, 1594438200000, 'Bernhard Viaduct', false);

-- students x 50
insert into students (name, image, notes, birthday, gender, is_delete) values ('Bo Crona', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', 'Fugit voluptatem ut quis neque eius rerum cum ut quisquam.', 1561982757930, 'Female', false);
insert into students (name, image, notes, birthday, gender, is_delete) values ('Maxime Steuber', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', 'Dolores quibusdam quas reiciendis voluptatem.', 1584539473121, 'Female', false);
insert into students (name, image, notes, birthday, gender, is_delete) values ('Amely Harvey', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', 'Iure et officiis quis reprehenderit quasi cumque esse omnis voluptatem.', 1579946419873, 'Male', false);
insert into students (name, image, notes, birthday, gender, is_delete) values ('Alanis Hettinger', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', 'Similique sunt eveniet sit.', 1591429734880, 'Male', false);
insert into students (name, image, notes, birthday, gender, is_delete) values ('Eleazar Skiles', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', 'Dolorem in sit molestiae aut dolorem ab deserunt deserunt.', 1575235268740, 'Male', false);
insert into students (name, image, notes, birthday, gender, is_delete) values ('Aubrey Larkin', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', 'Praesentium vero ab qui sunt temporibus molestiae possimus maxime.', 1564367194516, 'Female', false);
insert into students (name, image, notes, birthday, gender, is_delete) values ('Jordyn Stoltenberg', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', 'Incidunt in aperiam recusandae sit voluptas sunt velit eos est.', 1583534368509, 'Male', false);
insert into students (name, image, notes, birthday, gender, is_delete) values ('Devan Wilkinson', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', 'Dolores et molestias qui aperiam.', 1579226813847, 'Male', false);
insert into students (name, image, notes, birthday, gender, is_delete) values ('Shyann Abernathy', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', 'Perferendis aperiam asperiores deleniti assumenda quod dolor quaerat.', 1580756601849, 'Male', false);
insert into students (name, image, notes, birthday, gender, is_delete) values ('Shaun Conner', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', 'A dolores est eveniet atque dolorem omnis sapiente necessitatibus dolore.', 1567209860274, 'Male', false);
insert into students (name, image, notes, birthday, gender, is_delete) values ('Marge Schneider', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', 'Quaerat dolorem sed autem at quo unde ratione hic.', 1563159283639, 'Female', false);
insert into students (name, image, notes, birthday, gender, is_delete) values ('Hope Abbott', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', 'Fugit expedita veritatis eveniet est et dolorem.', 1578529393413, 'Female', false);
insert into students (name, image, notes, birthday, gender, is_delete) values ('Carleton Mills', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', 'Quaerat quisquam facilis aut dolore perspiciatis magni.', 1572704323236, 'Female', false);
insert into students (name, image, notes, birthday, gender, is_delete) values ('Mariano Little', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', 'Eligendi sunt consequatur veniam iste minus non animi culpa voluptatem.', 1578070982649, 'Female', false);
insert into students (name, image, notes, birthday, gender, is_delete) values ('Mossie Balistreri', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', 'Cupiditate magni sit.', 1590349476914, 'Male', false);
insert into students (name, image, notes, birthday, gender, is_delete) values ('Braulio Hand', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', 'Ex quibusdam non sed odit rerum expedita quo.', 1565091063487, 'Female', false);
insert into students (name, image, notes, birthday, gender, is_delete) values ('Isadore Connell', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', 'Aperiam quo hic dicta voluptas magnam commodi autem.', 1571208202251, 'Female', false);
insert into students (name, image, notes, birthday, gender, is_delete) values ('Cleta Kuhlman', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', 'Exercitationem animi esse est ut cum nobis alias autem.', 1574672153654, 'Female', false);
insert into students (name, image, notes, birthday, gender, is_delete) values ('Michelle Quitzon', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', 'Est et exercitationem facilis nostrum in soluta similique molestiae.', 1571743203792, 'Female', false);
insert into students (name, image, notes, birthday, gender, is_delete) values ('Sylvan Considine', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', 'Quidem eos officiis et odio recusandae ab.', 1569767329196, 'Female', false);
insert into students (name, image, notes, birthday, gender, is_delete) values ('Jaqueline Ferry', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', 'Quia illum beatae est et quo.', 1576373084348, 'Male', false);
insert into students (name, image, notes, birthday, gender, is_delete) values ('Jayne Hara', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', 'Commodi veniam aut dolore accusamus totam nemo fugiat ratione.', 1586612719289, 'Female', false);
insert into students (name, image, notes, birthday, gender, is_delete) values ('Loyal Veum', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', 'Dolores id possimus sunt.', 1577525320972, 'Female', false);
insert into students (name, image, notes, birthday, gender, is_delete) values ('Stefan Amore', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', 'Sunt sunt deleniti vitae est quod reiciendis a.', 1576815429664, 'Female', false);
insert into students (name, image, notes, birthday, gender, is_delete) values ('Karelle Zieme', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', 'In nihil fugiat autem.', 1584535997631, 'Male', false);
insert into students (name, image, notes, birthday, gender, is_delete) values ('Enos Quitzon', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', 'Ut qui et perspiciatis magni ut.', 1584909087405, 'Female', false);
insert into students (name, image, notes, birthday, gender, is_delete) values ('Meda Morar', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', 'Aut vitae sit est tempora.', 1583659562386, 'Female', false);
insert into students (name, image, notes, birthday, gender, is_delete) values ('Markus Welch', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', 'Sunt non molestias aperiam architecto qui officiis.', 1565083796121, 'Male', false);
insert into students (name, image, notes, birthday, gender, is_delete) values ('Jacklyn Goldner', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', 'Perspiciatis dolor sit cumque non commodi illum perferendis.', 1581725125241, 'Female', false);
insert into students (name, image, notes, birthday, gender, is_delete) values ('Arvid Kuhlman', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', 'Eos natus temporibus.', 1581821308061, 'Female', false);
insert into students (name, image, notes, birthday, gender, is_delete) values ('Lauretta Stoltenberg', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', 'Tenetur est ut.', 1581551550882, 'Male', false);
insert into students (name, image, notes, birthday, gender, is_delete) values ('Vena Spencer', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', 'Illo dolor quia blanditiis eum.', 1582210217141, 'Female', false);
insert into students (name, image, notes, birthday, gender, is_delete) values ('Mazie Schaden', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', 'Dolor placeat earum et est repudiandae sit maxime.', 1580634929240, 'Male', false);
insert into students (name, image, notes, birthday, gender, is_delete) values ('Lesley Jacobi', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', 'Id dolores officia.', 1591165028474, 'Female', false);
insert into students (name, image, notes, birthday, gender, is_delete) values ('Ludwig Hodkiewicz', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', 'Quidem nulla in ea esse ipsam.', 1567661188692, 'Male', false);
insert into students (name, image, notes, birthday, gender, is_delete) values ('Cordia Kris', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', 'Ut quos commodi numquam consequuntur possimus sint voluptatem accusantium.', 1591502541376, 'Female', false);
insert into students (name, image, notes, birthday, gender, is_delete) values ('Ila Considine', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', 'Tempora rerum nihil rem.', 1588182391670, 'Female', false);
insert into students (name, image, notes, birthday, gender, is_delete) values ('Rocio Zemlak', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', 'Architecto eos est.', 1566910022460, 'Female', false);
insert into students (name, image, notes, birthday, gender, is_delete) values ('Trystan Morar', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', 'Officia voluptas tenetur quia dolorem est libero suscipit quaerat non.', 1562377458920, 'Female', false);
insert into students (name, image, notes, birthday, gender, is_delete) values ('Katherine Stoltenberg', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', 'Dicta magni delectus sapiente amet qui.', 1575854388630, 'Male', false);
insert into students (name, image, notes, birthday, gender, is_delete) values ('Bernardo Predovic', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', 'Doloremque provident commodi debitis quia.', 1562736999786, 'Female', false);
insert into students (name, image, notes, birthday, gender, is_delete) values ('Harvey Fahey', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', 'Sapiente ex blanditiis quas voluptatem nostrum enim vel quo.', 1573621756607, 'Female', false);
insert into students (name, image, notes, birthday, gender, is_delete) values ('Sonya Mills', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', 'Voluptatem voluptatem velit animi et ipsum.', 1586697026840, 'Male', false);
insert into students (name, image, notes, birthday, gender, is_delete) values ('Reyes Romaguera', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', 'Sint vel voluptatem voluptate voluptatem ut commodi quia.', 1565850335922, 'Male', false);
insert into students (name, image, notes, birthday, gender, is_delete) values ('Salvador Strosin', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', 'Autem sint et sint quis aut qui nostrum temporibus quia.', 1577150826673, 'Male', false);
insert into students (name, image, notes, birthday, gender, is_delete) values ('Jeanne Spencer', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', 'Et iure dolorem modi quisquam libero perspiciatis saepe blanditiis.', 1575886485436, 'Male', false);
insert into students (name, image, notes, birthday, gender, is_delete) values ('Donnell Jones', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', 'Exercitationem odio ut consequatur ea aliquid eligendi.', 1576697511995, 'Female', false);
insert into students (name, image, notes, birthday, gender, is_delete) values ('Johnson Reilly', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', 'Et iure laboriosam cum qui ea.', 1561937897436, 'Female', false);
insert into students (name, image, notes, birthday, gender, is_delete) values ('Jessyca Parker', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', 'Et accusantium quo assumenda quasi esse et atque mollitia et.', 1584259169398, 'Female', false);
insert into students (name, image, notes, birthday, gender, is_delete) values ('Noble Howe', 'http://via.placeholder.com/300/CCCCCC/969696/?text=Sample%20Image', 'Non reprehenderit distinctio animi natus molestiae.', 1580235076309, 'Male', false);

-- attendance class 1
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (1, 1, 1, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (1, 2, 1, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (1, 3, 1, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (1, 4, 1, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (1, 1, 2, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (1, 2, 2, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (1, 3, 2, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (1, 4, 2, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (1, 1, 3, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (1, 2, 3, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (1, 3, 3, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (1, 4, 3, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (1, 1, 4, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (1, 2, 4, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (1, 3, 4, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (1, 4, 4, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (1, 1, 5, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (1, 2, 5, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (1, 3, 5, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (1, 4, 5, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (1, 1, 6, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (1, 2, 6, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (1, 3, 6, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (1, 4, 6, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (1, 1, 7, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (1, 2, 7, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (1, 3, 7, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (1, 4, 7, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (1, 1, 8, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (1, 2, 8, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (1, 3, 8, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (1, 4, 8, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (1, 1, 9, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (1, 2, 9, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (1, 3, 9, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (1, 4, 9, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (1, 1, 10, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (1, 2, 10, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (1, 3, 10, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (1, 4, 10, false, '', 0, '');

-- attendance class 2
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 5, 11, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 6, 11, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 7, 11, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 8, 11, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 9, 11, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 10, 11, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 11, 11, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 12, 11, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 13, 11, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 14, 11, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 15, 11, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 16, 11, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 5, 12, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 6, 12, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 7, 12, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 8, 12, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 9, 12, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 10, 12, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 11, 12, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 12, 12, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 13, 12, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 14, 12, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 15, 12, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 16, 12, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 5, 13, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 6, 13, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 7, 13, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 8, 13, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 9, 13, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 10, 13, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 11, 13, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 12, 13, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 13, 13, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 14, 13, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 15, 13, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 16, 13, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 5, 14, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 6, 14, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 7, 14, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 8, 14, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 9, 14, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 10, 14, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 11, 14, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 12, 14, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 13, 14, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 14, 14, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 15, 14, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 16, 14, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 5, 15, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 6, 15, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 7, 15, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 8, 15, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 9, 15, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 10, 15, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 11, 15, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 12, 15, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 13, 15, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 14, 15, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 15, 15, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 16, 15, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 5, 16, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 6, 16, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 7, 16, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 8, 16, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 9, 16, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 10, 16, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 11, 16, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 12, 16, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 13, 16, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 14, 16, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 15, 16, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 16, 16, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 5, 17, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 6, 17, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 7, 17, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 8, 17, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 9, 17, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 10, 17, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 11, 17, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 12, 17, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 13, 17, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 14, 17, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 15, 17, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 16, 17, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 5, 18, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 6, 18, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 7, 18, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 8, 18, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 9, 18, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 10, 18, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 11, 18, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 12, 18, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 13, 18, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 14, 18, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 15, 18, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 16, 18, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 5, 19, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 6, 19, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 7, 19, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 8, 19, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 9, 19, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 10, 19, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 11, 19, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 12, 19, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 13, 19, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 14, 19, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 15, 19, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 16, 19, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 5, 20, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 6, 20, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 7, 20, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 8, 20, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 9, 20, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 10, 20, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 11, 20, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 12, 20, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 13, 20, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 14, 20, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 15, 20, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (2, 16, 20, false, '', 0, '');

-- attendance class 3
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (3, 17, 21, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (3, 18, 21, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (3, 19, 21, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (3, 20, 21, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (3, 17, 22, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (3, 18, 22, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (3, 19, 22, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (3, 20, 22, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (3, 17, 23, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (3, 18, 23, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (3, 19, 23, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (3, 20, 23, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (3, 17, 24, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (3, 18, 24, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (3, 19, 24, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (3, 20, 24, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (3, 17, 25, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (3, 18, 25, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (3, 19, 25, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (3, 20, 25, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (3, 17, 26, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (3, 18, 26, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (3, 19, 26, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (3, 20, 26, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (3, 17, 27, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (3, 18, 27, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (3, 19, 27, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (3, 20, 27, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (3, 17, 28, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (3, 18, 28, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (3, 19, 28, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (3, 20, 28, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (3, 17, 29, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (3, 18, 29, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (3, 19, 29, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (3, 20, 29, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (3, 17, 30, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (3, 18, 30, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (3, 19, 30, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (3, 20, 30, false, '', 0, '');

-- attendance class 4
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 21, 31, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 22, 31, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 23, 31, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 24, 31, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 25, 31, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 26, 31, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 27, 31, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 28, 31, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 21, 32, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 22, 32, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 23, 32, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 24, 32, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 25, 32, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 26, 32, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 27, 32, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 28, 32, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 21, 33, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 22, 33, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 23, 33, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 24, 33, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 25, 33, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 26, 33, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 27, 33, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 28, 33, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 21, 34, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 22, 34, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 23, 34, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 24, 34, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 25, 34, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 26, 34, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 27, 34, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 28, 34, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 21, 35, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 22, 35, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 23, 35, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 24, 35, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 25, 35, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 26, 35, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 27, 35, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 28, 35, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 21, 36, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 22, 36, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 23, 36, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 24, 36, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 25, 36, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 26, 36, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 27, 36, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 28, 36, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 21, 37, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 22, 37, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 23, 37, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 24, 37, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 25, 37, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 26, 37, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 27, 37, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 28, 37, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 21, 38, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 22, 38, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 23, 38, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 24, 38, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 25, 38, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 26, 38, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 27, 38, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 28, 38, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 21, 39, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 22, 39, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 23, 39, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 24, 39, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 25, 39, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 26, 39, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 27, 39, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 28, 39, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 21, 40, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 22, 40, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 23, 40, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 24, 40, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 25, 40, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 26, 40, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 27, 40, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (4, 28, 40, false, '', 0, '');

-- attendance class 5
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (5, 29, 41, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (5, 30, 41, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (5, 31, 41, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (5, 32, 41, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (5, 29, 42, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (5, 30, 42, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (5, 31, 42, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (5, 32, 42, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (5, 29, 43, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (5, 30, 43, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (5, 31, 43, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (5, 32, 43, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (5, 29, 44, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (5, 30, 44, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (5, 31, 44, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (5, 32, 44, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (5, 29, 45, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (5, 30, 45, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (5, 31, 45, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (5, 32, 45, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (5, 29, 46, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (5, 30, 46, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (5, 31, 46, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (5, 32, 46, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (5, 29, 47, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (5, 30, 47, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (5, 31, 47, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (5, 32, 47, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (5, 29, 48, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (5, 30, 48, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (5, 31, 48, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (5, 32, 48, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (5, 29, 49, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (5, 30, 49, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (5, 31, 49, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (5, 32, 49, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (5, 29, 50, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (5, 30, 50, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (5, 31, 50, false, '', 0, '');
insert into attendance (class_id, session_id, student_id, is_present, remarks, is_late, document ) values (5, 32, 50, false, '', 0, '');


-- instructors_classes
insert into instructors_classes (instructor_id, session_id, class_id) values (1, 1, 1);
insert into instructors_classes (instructor_id, session_id, class_id) values (1, 2, 1);
insert into instructors_classes (instructor_id, session_id, class_id) values (1, 3, 1);
insert into instructors_classes (instructor_id, session_id, class_id) values (1, 4, 1);
insert into instructors_classes (instructor_id, session_id, class_id) values (2, 5, 2);
insert into instructors_classes (instructor_id, session_id, class_id) values (2, 6, 2);
insert into instructors_classes (instructor_id, session_id, class_id) values (2, 7, 2);
insert into instructors_classes (instructor_id, session_id, class_id) values (2, 8, 2);
insert into instructors_classes (instructor_id, session_id, class_id) values (2, 9, 2);
insert into instructors_classes (instructor_id, session_id, class_id) values (2, 10, 2);
insert into instructors_classes (instructor_id, session_id, class_id) values (2, 11, 2);
insert into instructors_classes (instructor_id, session_id, class_id) values (2, 12, 2);
insert into instructors_classes (instructor_id, session_id, class_id) values (2, 13, 2);
insert into instructors_classes (instructor_id, session_id, class_id) values (2, 14, 2);
insert into instructors_classes (instructor_id, session_id, class_id) values (2, 15, 2);
insert into instructors_classes (instructor_id, session_id, class_id) values (2, 16, 2);
insert into instructors_classes (instructor_id, session_id, class_id) values (3, 17, 3);
insert into instructors_classes (instructor_id, session_id, class_id) values (3, 18, 3);
insert into instructors_classes (instructor_id, session_id, class_id) values (3, 19, 3);
insert into instructors_classes (instructor_id, session_id, class_id) values (3, 20, 3);
insert into instructors_classes (instructor_id, session_id, class_id) values (4, 21, 4);
insert into instructors_classes (instructor_id, session_id, class_id) values (4, 22, 4);
insert into instructors_classes (instructor_id, session_id, class_id) values (4, 23, 4);
insert into instructors_classes (instructor_id, session_id, class_id) values (4, 24, 4);
insert into instructors_classes (instructor_id, session_id, class_id) values (4, 25, 4);
insert into instructors_classes (instructor_id, session_id, class_id) values (4, 26, 4);
insert into instructors_classes (instructor_id, session_id, class_id) values (4, 27, 4);
insert into instructors_classes (instructor_id, session_id, class_id) values (4, 28, 4);
insert into instructors_classes (instructor_id, session_id, class_id) values (5, 29, 5);
insert into instructors_classes (instructor_id, session_id, class_id) values (5, 30, 5);
insert into instructors_classes (instructor_id, session_id, class_id) values (5, 31, 5);
insert into instructors_classes (instructor_id, session_id, class_id) values (5, 32, 5);
